import os
import sys
from   pathlib import Path
import re
import tyro
from   glob import glob
from   itertools import chain

sys.path.append(os.path.normcase(Path(__file__).resolve().parents[2]))
from   calib_move.core.containers import CLIArgs


def main_synth(argv=None):
    CLIARGS = tyro.cli(CLIArgs, args=argv)
    CLIARGS.sanitize()
    
    print("sanitization successful! \n")
    print(CLIARGS)
    

if __name__ == "__main__":
    os.system("cls" if os.name == "nt" else "clear")

    argv = [
        # show tyro autogenerated help message
        # "-h",
        
        # path to some dummy video or folder containing videos
        "--input-video-path", "H:/code_elias/random_scrips_balgrist/test_videos/",
        
        # use one of the four methods to specify the static window
        "--static-window",    "H:/code_elias/balgrist-calib-move/tests/test_static_window_template.json",
        # "--static-window",    "START-00:00:00",
        # "--static-window",    "00:00:00-END",
        # "--static-window",    "00:00:00-00:01:00",   
        
        # optional arguments
        # ...    
    ]
    
    # dummy main function to simulate parsing cli arguments
    main_synth(argv=argv)

    
    
    

